"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.updateUserRouterPath = exports.updateTagRouterPath = exports.updateLinkRouterPath = exports.updateCollectionRouterPath = exports.startResestPassword = exports.registerRouterPath = exports.newTagRouterPath = exports.newLinkRouterPath = exports.newCollectionRouterPath = exports.logoutRouterPath = exports.loginRouterPath = exports.getUserRouterPath = exports.getTagRouterPath = exports.getLinkRouterPath = exports.getCollectionRouterPath = exports.getCollectionImageTypeRouterPath = exports.getCollectionImageRouterPath = exports.endResestPassword = exports.deleteUserRouterPath = exports.deleteTagRouterPath = exports.deleteLinkRouterPath = exports.deleteCollectionRouterPath = exports.checkEmailExists = exports.allUserRouterPath = exports.allUserCollectionsRouterPath = exports.allLinkRouterPath = exports.addTagToCollectionRouterPath = void 0;
var root = '/api';
var loginRouterPath = root + '/login';
exports.loginRouterPath = loginRouterPath;
var logoutRouterPath = root + '/logout';
exports.logoutRouterPath = logoutRouterPath;
var registerRouterPath = root + '/register';
exports.registerRouterPath = registerRouterPath;
var startResestPassword = root + '/start/reset';
exports.startResestPassword = startResestPassword;
var endResestPassword = root + '/end/reset';
exports.endResestPassword = endResestPassword;
var checkEmailExists = root + '/check/email'; // const newUserRouterPath = root + '/user/new';

exports.checkEmailExists = checkEmailExists;
var allUserRouterPath = root + '/user/all';
exports.allUserRouterPath = allUserRouterPath;
var getUserRouterPath = root + '/user';
exports.getUserRouterPath = getUserRouterPath;
var updateUserRouterPath = root + '/user/update';
exports.updateUserRouterPath = updateUserRouterPath;
var deleteUserRouterPath = root + '/user/:id';
exports.deleteUserRouterPath = deleteUserRouterPath;
var newCollectionRouterPath = root + '/collection/new';
exports.newCollectionRouterPath = newCollectionRouterPath;
var allUserCollectionsRouterPath = root + '/collection/all';
exports.allUserCollectionsRouterPath = allUserCollectionsRouterPath;
var getCollectionRouterPath = root + '/collection/:id';
exports.getCollectionRouterPath = getCollectionRouterPath;
var getCollectionImageTypeRouterPath = root + '/collection/image/:id/:type';
exports.getCollectionImageTypeRouterPath = getCollectionImageTypeRouterPath;
var getCollectionImageRouterPath = root + '/collection/image/:id';
exports.getCollectionImageRouterPath = getCollectionImageRouterPath;
var addTagToCollectionRouterPath = root + '/collection/tag';
exports.addTagToCollectionRouterPath = addTagToCollectionRouterPath;
var updateCollectionRouterPath = root + '/collection/:id';
exports.updateCollectionRouterPath = updateCollectionRouterPath;
var deleteCollectionRouterPath = root + '/collection/:id';
exports.deleteCollectionRouterPath = deleteCollectionRouterPath;
var newLinkRouterPath = root + '/link/new';
exports.newLinkRouterPath = newLinkRouterPath;
var allLinkRouterPath = root + '/link/all';
exports.allLinkRouterPath = allLinkRouterPath;
var getLinkRouterPath = root + '/link/:id';
exports.getLinkRouterPath = getLinkRouterPath;
var updateLinkRouterPath = root + '/link/:id';
exports.updateLinkRouterPath = updateLinkRouterPath;
var deleteLinkRouterPath = root + '/link/:id';
exports.deleteLinkRouterPath = deleteLinkRouterPath;
var newTagRouterPath = root + '/tag/new';
exports.newTagRouterPath = newTagRouterPath;
var getTagRouterPath = root + '/tag/:id';
exports.getTagRouterPath = getTagRouterPath;
var updateTagRouterPath = root + '/tag/:id';
exports.updateTagRouterPath = updateTagRouterPath;
var deleteTagRouterPath = root + '/tag/:id';
exports.deleteTagRouterPath = deleteTagRouterPath;